<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxYvo6P\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxYvo6P/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGxYvo6P.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGxYvo6P\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGxYvo6P\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GxYvo6P',
    'container.build_id' => '8a0fb157',
    'container.build_time' => 1618065595,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxYvo6P');
