<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXrTfWh1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXrTfWh1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXrTfWh1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXrTfWh1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXrTfWh1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XrTfWh1',
    'container.build_id' => 'c95271c1',
    'container.build_time' => 1617658771,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXrTfWh1');
