<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR3qpjcZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR3qpjcZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR3qpjcZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR3qpjcZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerR3qpjcZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'R3qpjcZ',
    'container.build_id' => '71704242',
    'container.build_time' => 1616701620,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR3qpjcZ');
